imports:
- path: couchbase.py

resources:
- name: couchbase
  type: couchbase.py
  properties:
    serverVersion: '5.5.0'
    serverNodeCount: 3
    serverNodeType: 'n1-standard-1'
    serverDiskSize: 500
    syncGatewayVersion: '2.0.0'
    syncGatewayNodeCount: 1
    syncGatewayNodeType: 'n1-standard-1'
    syncGatewayDiskSize: 500

outputs:
- name: username
  value: $(ref.couchbase.couchbaseUsername)
- name: password
  value: $(ref.couchbase.couchbasePassword)
- name: serverAdminUrl
  value: $(ref.couchbase.serverAdminUrl)
- name: syncGatewayAdminUrl
  value: $(ref.couchbase.syncGatewayAdminUrl)
